---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: patch-dspa
  namespace: redhat-ods-applications
spec:
  schedule: '*/2 * * * *'
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dspa-patch
              # Custom image to provide oc cli and jq
              image: quay.io/modh/dspa-patch:latest
              env: []
              command: ["patch-dspa.sh"]
          serviceAccount: data-science-pipelines-operator-controller-manager
          serviceAccountName: data-science-pipelines-operator-controller-manager
          restartPolicy: Never
